version: "3.8"

services:
  myapp:
    build:
      context: .
      dockerfile: Dockerfile
    image: nexus.local:5000/app:latest
    ports:
      - "8000:80"
    networks:
      - monitoring

  # database:
  #   image: postgres:${POSTGRES_VERSION:-16}-alpine
  #   environment:
  #     POSTGRES_DB: ${POSTGRES_DB:-app}
  #     POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-!ChangeMe!}
  #     POSTGRES_USER: ${POSTGRES_USER:-app}
  #   healthcheck:
  #     test: ["CMD", "pg_isready", "-d", "${POSTGRES_DB:-app}", "-U", "${POSTGRES_USER:-app}"]
  #     timeout: 5s
  #     retries: 5
  #     start_period: 60s
  #   ports:
  #     - "5432"
  #   volumes:
  #     - database_data:/var/lib/postgresql/data:rw

  # mailer:
  #   image: axllent/mailpit
  #   ports:
  #     - "1025"
  #     - "8025"
  #   environment:
  #     MP_SMTP_AUTH_ACCEPT_ANY: 1
  #     MP_SMTP_AUTH_ALLOW_INSECURE: 1

volumes:
  database_data:

networks:
  monitoring:
    external: true
